services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: database-api_teste_tecnico
    environment:
      MYSQL_DATABASE: desafio_api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
